export const TEXTOS_GENERAL = {
  appNombre: 'Traxo',
  cargando: 'Cargando...',
  error: 'Algo salió mal. Intenta de nuevo.',
  reintentar: 'Reintentar',
  cancelar: 'Cancelar',
  guardar: 'Guardar',
  cerrar: 'Cerrar',
} as const;

export const TEXTOS_RASTREO = {
  titulo: 'Rastrear Transferencia',
  subtitulo: 'Sube tu comprobante o ingresa los datos manualmente',
  botonConsultar: 'Consultar',
  botonSubirImagen: 'Subir comprobante',
  placeholderBanco: 'Selecciona un banco',
  placeholderMonto: '0.00',
  placeholderClaveRastreo: 'Ej. MBAN0100...',
  placeholderCuenta: 'CLABE o número de cuenta',
  etiquetaFecha: 'Fecha de operación',
  etiquetaBancoEmisor: 'Banco emisor',
  etiquetaBancoReceptor: 'Banco receptor',
  etiquetaCuenta: 'Cuenta beneficiaria',
  etiquetaMonto: 'Monto',
  etiquetaClaveRastreo: 'Clave de rastreo',
  ocrExito: 'Datos extraídos del comprobante. Verifica antes de consultar.',
  enlaceLogin: 'Iniciar Sesión',
  modoComprobante: 'Comprobante',
  modoManual: 'Manual',
  uploadHint: 'Arrastra tu comprobante o toca para seleccionar',
  uploadFormatos: 'JPG · PNG · WEBP',
  uploadBoton: 'Seleccionar archivo',
  uploadTipCampos: 'Asegúrate de que el comprobante muestre claramente: fecha, monto, clave de rastreo y bancos emisor y receptor.',
  ingresarManual: 'Ingresar datos manualmente',
  etiquetaDatosCompletos: 'Datos completos',
  hintDatosCompletos: 'Incluye nombre del ordenante, beneficiario y concepto (más lento)',
  ocrAnalizando: 'Analizando comprobante…',
  ocrError: 'No se pudo analizar la imagen. Ingrésalos manualmente.',
  ocrFaltantesTitulo: 'No se pudieron leer los siguientes datos:',
  ocrFaltantesHint: 'Por favor, ingrésalos manualmente.',
} as const;

export const TEXTOS_RESULTADO = {
  titulo: 'Resultado',
  estadoLiquidada: 'Liquidada',
  estadoRechazada: 'Rechazada',
  estadoEnProceso: 'En proceso',
  estadoNoEncontrada: 'No encontrada',
  botonGuardarHistorial: 'Guardar en historial',
  botonGuardarPendiente: 'Guardar para verificar después',
  botonNuevaConsulta: 'Nueva consulta',
  guardadoExito: 'Guardado en historial',
  errorGuardado: 'No se pudo guardar. Intenta de nuevo.',
  placeholderAlias: 'Alias opcional (ej. Renta enero)',
  etiquetaEmisor: 'Banco emisor',
  etiquetaReceptor: 'Banco receptor',
  etiquetaMonto: 'Monto',
  etiquetaFecha: 'Fecha',
  etiquetaEstado: 'Estado',
  etiquetaNombreEmisor: 'Ordenante',
  etiquetaNombreReceptor: 'Beneficiario',
  etiquetaConcepto: 'Concepto',
  notaPrivacidad: 'Guardamos banco, monto, fecha y concepto (si viene). Nunca nombres ni CLABE.',
  sugerenciaSinDatosCompletos: '¿Puede existir pero aún no estar liquidada? Intenta buscar sin "Datos completos".',
} as const;

export const TEXTOS_HISTORIAL = {
  titulo: 'Historial',
  vacio: 'Aun no tienes consultas guardadas',
  vacioCta: 'Realiza tu primera consulta',
  placeholderAlias: 'Ej. Renta enero',
  botonReverificar: 'Re-verificar',
  hintReverificar: 'Se pre-llenarán los datos guardados. Completa la clave de rastreo y la cuenta.',
  botonEliminar: 'Eliminar',
  confirmarEliminarTitulo: '¿Eliminar del historial?',
  confirmarEliminarMensaje: 'Se eliminará este registro de forma permanente.',
  confirmarEliminarBoton: 'Sí, eliminar',
} as const;

export const TEXTOS_AUTH = {
  tituloLogin: 'Iniciar Sesión',
  tituloRegistro: 'Crear Cuenta',
  subtituloLogin: 'Rastreador de Transferencias SPEI',
  subtituloRegistro: 'Crea tu Cuenta Gratis',
  etiquetaNombre: 'Nombre',
  etiquetaEmail: 'Correo electrónico',
  etiquetaContrasena: 'Contraseña',
  placeholderNombre: 'Tu nombre',
  placeholderEmail: 'tu@correo.com',
  placeholderContrasena: '••••••••',
  placeholderContrasenaNueva: 'Mínimo 8 caracteres',
  botonLogin: 'Entrar',
  botonRegistro: 'Crear Cuenta',
  preguntaSinCuenta: '¿No tienes cuenta?',
  preguntaTieneCuenta: '¿Ya tienes cuenta?',
  enlaceRegistroTexto: 'Regístrate',
  enlaceLoginTexto: 'Inicia Sesión',
  consultarSinCuenta: 'Consultar sin Cuenta',
  avisoPrivacidad: 'Aviso de Privacidad',
  enlaceRegistro: '¿No tienes cuenta? Regístrate',
  enlaceLogin: '¿Ya tienes cuenta? Inicia Sesión',
  enlaceOlvideContrasena: 'Olvide mi Contraseña',
} as const;

export const TEXTOS_PERFIL = {
  titulo: 'Perfil',
  etiquetaNombre: 'Nombre',
  placeholderNombre: 'Tu nombre',
  botonGuardar: 'Guardar cambios',
  botonCambiarContrasena: 'Cambiar contraseña',
  contrasenaActual: 'Contraseña actual',
  contrasenaNueva: 'Nueva contraseña',
  botonEliminarCuenta: 'Eliminar cuenta',
  confirmacionEliminar: '¿Seguro que quieres eliminar tu cuenta? Esta acción es irreversible.',
  confirmarEliminarTitulo: '¿Eliminar cuenta?',
  confirmarEliminarBoton: 'Sí, eliminar',
  exitoNombre: 'Nombre actualizado correctamente',
  exitoContrasena: 'Contraseña cambiada correctamente',
  botonCerrarSesion: 'Cerrar Sesión',
  zonaPeligro: 'Zona de Peligro',
} as const;

export const TEXTOS_ERRORES = {
  campoRequerido: 'Este campo es requerido',
  emailInvalido: 'Ingresa un correo electrónico válido',
  montoInvalido: 'El monto debe ser un número válido (ej. 1300.00)',
  fechaInvalida: 'El formato de fecha debe ser dd/mm/aaaa',
  noAutenticado: 'Tu sesion expiró. Inicia sesión de nuevo.',
  sinConexion: 'Sin conexión. Verifica tu red.',
  banxicoNoDisponible: 'El portal de Banxico no está disponible en este momento.',
  transaccionNoEncontrada: 'No se encontró la transferencia con los datos proporcionados.',
  contrasenaMinimo: 'La contraseña debe tener al menos 8 caracteres',
  credencialesIncorrectas: 'Correo o contraseña incorrectos.',
} as const;

export const TEXTOS_NAV = {
  rastreo: 'Rastrear',
  historial: 'Historial',
  perfil: 'Perfil',
  cerrarSesion: 'Cerrar Sesión',
} as const;

export const TEXTOS_SOPORTE = {
  ariaBoton:  'Soporte y contacto',
  titulo:     'Soporte y contacto',
  mensaje:    '¿Tienes dudas, sugerencias o alguna queja?\nEscríbenos y te respondemos a la brevedad.',
  email:      'soporte@traxo.mx',
  cerrar:     'Cerrar',
} as const;

export const TEXTOS_AVISO = {
  titulo: 'Aviso de Privacidad',
  tituloPagina: 'Traxo — Aviso de Privacidad',
  intro: 'Traxo es un rastreador de transferencias SPEI. Usamos la información estrictamente necesaria para que el servicio funcione y jamás la compartimos con terceros.',
  seccionRecopilados: 'Datos que recopilamos',
  seccionNunca: 'Datos que NUNCA almacenamos',
  seccionArco: 'Tus derechos (ARCO)',
  arcoTexto1: 'Puedes ejercer tus derechos de Acceso, Rectificación, Cancelación u Oposición escribiendo a',
  arcoEmail: 'soporte@traxo.mx',
  arcoTexto2: 'Tambien puedes eliminar tu cuenta desde la sección',
  arcoSeccionPerfil: 'Perfil',
  arcoTexto2Fin: 'lo que borra todos tus datos de forma inmediata e irreversible.',
  volverRastrear: 'Volver a rastrear',
} as const;
